FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Talongte123
ENV GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
ENV N8N_ENCRYPTION_KEY=ADFASZXZ532G454543

EXPOSE 5678
CMD ["n8n", "start"]
